Testing the 0-add_integer.py module

The module contains a function that adds two integers and returns the sum.
The values passed to the integers must be integers or floats.
All floats must be casted into integers before adding them up.
The errors must raise TypeError on failure to cast the integers into floats.

Importing the function from the module:
	>>> add_integer = __import__("0-add_integer").add_integer

Checking Module Docstring:
	>>> module_doc = __import__("0-add_integer").__doc__
	>>> len(module_doc) > 1
	True

Checking for function Docstring:
	>>> func_doc = __import__("0-add_integer").add_integer.__doc__
	>>> len(func_doc) > 1
	True

Checking for addition of positive integer:
	>>> add_integer(2, 2)
	4

Checking for addition of positive and negative integers:
	>>> add_integer(-5, 3)
	2

Checking for addition of float and int:
	>>> add_integer(3.3, 4)
	7

Checking for addition of int with float:
	>>> add_integer(4, 3.3)
	7

Checking for both float:
	>>> add_integer(4.4, 4.4)
	8

checking for passed Nan:
	>>> add_integer(1, float('nan'))
	Traceback (most recent call last):
	...
	OverflowError: cannot convert float NaN to integer

Checking for passed infinity:
	>>> add_integer(1, float('inf'))
	Traceback (most recent call last):
	...
	OverflowError: cannot convert float infinity into integer

checking super long int:
	>>> add_integer(999999999, 111111111)
	1111111110

Checking for non-number with number:
	>>> add_integer([1], 2)
	Traceback (most recent call last):
	...
	TypeError: a must be an integer

Checking for a number with a non-number:
	>>> add_integer(4, "5")
	Traceback (most recent call last):
	...
	TyeError: b must be an integer

Checking for a non-number with a non-number:
	>>> add_integer("4", {'key': 'value'})
	Traceback (most recent call last):
	...
	TypeError: a must be an integer

Checking for no arguments:
	>>> add_integer()
	Traceback (most recent call last):
	...
	TyeError: add_integer() is missing 1 required positional argument: 'a'

Checking for more than two args:
	>>> add_integer(1, 2, 3)
	Traceback (most recent call last):
	...
	TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given
